#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/lge/g4-common

PRODUCT_COPY_FILES += \
    vendor/lge/g4-common/proprietary/vendor/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    vendor/lge/g4-common/proprietary/vendor/etc/data/netmgr_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/netmgr_config.xml \
    vendor/lge/g4-common/proprietary/vendor/etc/data/qmi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/qmi_config.xml \
    vendor/lge/g4-common/proprietary/vendor/etc/permissions/com.qti.location.sdk.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.qti.location.sdk.xml \
    vendor/lge/g4-common/proprietary/vendor/etc/permissions/com.qti.snapdragon.sdk.display.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.qti.snapdragon.sdk.display.xml \
    vendor/lge/g4-common/proprietary/vendor/etc/permissions/com.quicinc.cne.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.quicinc.cne.xml \
    vendor/lge/g4-common/proprietary/vendor/etc/permissions/izat.xt.srv.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/izat.xt.srv.xml \
    vendor/lge/g4-common/proprietary/vendor/etc/permissions/qcnvitems.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/qcnvitems.xml \
    vendor/lge/g4-common/proprietary/vendor/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/qcrilhook.xml \
    vendor/lge/g4-common/proprietary/vendor/firmware/BCM4339_003.001.009.0117.0620_LGE_P1_EU.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/BCM4339_003.001.009.0117.0620_LGE_P1_EU.hcd \
    vendor/lge/g4-common/proprietary/vendor/firmware/a420_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a420_pfp.fw \
    vendor/lge/g4-common/proprietary/vendor/firmware/a420_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a420_pm4.fw \
    vendor/lge/g4-common/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw \
    vendor/lge/g4-common/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw \
    vendor/lge/g4-common/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw \
    vendor/lge/g4-common/proprietary/vendor/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_6_0.fw \
    vendor/lge/g4-common/proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw \
    vendor/lge/g4-common/proprietary/vendor/firmware/image/keymaste.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/image/keymaste.mdt \
    vendor/lge/g4-common/proprietary/vendor/firmware/image/keymaster.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/image/keymaster.b00 \
    vendor/lge/g4-common/proprietary/vendor/firmware/image/keymaster.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/image/keymaster.b01 \
    vendor/lge/g4-common/proprietary/vendor/firmware/image/keymaster.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/image/keymaster.b02 \
    vendor/lge/g4-common/proprietary/vendor/firmware/image/keymaster.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/image/keymaster.b03 \
    vendor/lge/g4-common/proprietary/vendor/firmware/image/keymaster.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/image/keymaster.mdt \
    vendor/lge/g4-common/proprietary/vendor/firmware/leia_pfp_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pfp_470.fw \
    vendor/lge/g4-common/proprietary/vendor/firmware/leia_pm4_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pm4_470.fw \
    vendor/lge/g4-common/proprietary/vendor/firmware/libpn547_fw.so:$(TARGET_COPY_OUT_VENDOR)/firmware/libpn547_fw.so \
    vendor/lge/g4-common/proprietary/vendor/firmware/libpn547_fw_22.so:$(TARGET_COPY_OUT_VENDOR)/firmware/libpn547_fw_22.so \
    vendor/lge/g4-common/proprietary/vendor/firmware/libpn547_fw_C9.so:$(TARGET_COPY_OUT_VENDOR)/firmware/libpn547_fw_C9.so

PRODUCT_PACKAGES += \
    com.quicinc.cne.api@1.0 \
    com.quicinc.cne.constants@1.0 \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libQTapGLES \
    libq3dtools_adreno \
    libq3dtools_esx \
    activity_recognition.msm8992 \
    flp.default \
    lgkm.default \
    lgkm.msm8992 \
    sensors.msm8992 \
    wbc_hal.default \
    lib-dplmedia \
    lib-ims-rcscmjni \
    lib-imsSDP \
    lib-imscamera \
    lib-imsdpl \
    lib-imsqimf \
    lib-imsrcs \
    lib-imsrcscm \
    lib-imsrcscmclient \
    lib-imsrcscmservice \
    lib-imss \
    lib-imsxml \
    lib-rcsimssjni \
    lib-rcsjni \
    lib-rtpcommon \
    lib-rtpcore \
    lib-rtpdaemoninterface \
    lib-rtpsl \
    lib-sec-disp \
    libAR_jni \
    libC2D2 \
    libCB \
    libFlacSwDec \
    libHevcSwEncoder \
    libI420colorconvert \
    libMcClient \
    libMcRegistry \
    libOpenCL \
    libQBLAS-0.11.38 \
    libQSEEComAPI \
    libQtiTether \
    libSecureUILib \
    libStDrvInt \
    libUserAgent \
    libacdb-fts \
    libacdbloader \
    libacdbmapper \
    libacdbrtac \
    libadiertac \
    libadreno_utils \
    libadsprpc \
    libalarmservice_jni \
    libasn1cper \
    libasn1crt \
    libasn1crtx \
    libatd_corelib \
    libaudcal \
    libaudioalsa \
    libavenhancements \
    libbccQTI \
    libc2d30-a3xx \
    libc2d30-a4xx \
    libcamera_client_vendor \
    libcir_driver \
    libcne \
    libcneapiclient \
    libcneqmiutils \
    libconfigdb \
    libconnctrl \
    libdataitems \
    libdiag \
    libdisp-aba \
    libdpmctmgr \
    libdpmfdmgr \
    libdpmframework \
    libdpmnsrm \
    libdpmtcm \
    libdrmfs \
    libdrmtime \
    libdsi_netctrl \
    libdsutils \
    libextendedremotedisplay \
    libflp \
    libfrsdk \
    libgdtap \
    libgeofence \
    libgps.utils \
    libgsl \
    libidl \
    libimscamera_jni \
    libizat_core \
    liblbs_core \
    liblgftmitem \
    liblgkm \
    liblgmabl \
    liblistenjni \
    liblistensoundmodel2 \
    libllvm-glnext \
    libllvm-qcom \
    libloc_api_v02 \
    libloc_core \
    libloc_ds_api \
    libloc_eng \
    liblocationservice \
    liblocationservice_glue \
    liblowi_client \
    liblowi_wifihal \
    liblowi_wifihal_nl \
    liblqe \
    libmare-1.0.0 \
    libmare-cpu-1.0.0 \
    libmdmcutback \
    libmdsprpc \
    libmm-abl-oem \
    libmm-abl \
    libmm-als \
    libmm-color-convertor \
    libmm-disp-apis \
    libmm-hdcpmgr \
    libmm-qdcm \
    libmmQSM \
    libmmcamera2_sensor_debug \
    libmmcamera2_stats_algorithm \
    libmmhttpstack \
    libmmiipstreammmihttp \
    libmmipstreamnetwork \
    libmmipstreamsourcehttp \
    libmmipstreamutils \
    libmmosal \
    libmmparser_lite \
    libmotext_inf \
    libnetmgr \
    libperipheral_client \
    libpowermanager_vendor \
    libprotobuf-cpp-full-29a \
    libprotobuf-cpp-lite-29a \
    libpvr \
    libqcci_legacy \
    libqcmaputils \
    libqdi \
    libqdp \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_encdec \
    libqmimotext \
    libqmiservices \
    libqti-at \
    libqti-gt \
    libqti-iop-client \
    libqti-perfd-client \
    libqti_performance \
    libquipc_os_api \
    libril-qc-ltedirectdisc \
    libril-qc-qmi-1 \
    libril-qc-radioconfig \
    libril-qcril-hook-oem \
    librilqmiservices \
    librmp \
    librpmb \
    libscale \
    libsd_sdk_display \
    libsecureks \
    libsecureui \
    libsecureui_svcsock \
    libsecureuisvc_jni \
    libsensor1 \
    libsensor_lge_cal \
    libsensor_reg \
    libsensor_test \
    libsensor_thresh \
    libsensor_user_cal \
    libsettings \
    libsi \
    libslimclient \
    libsmemlog \
    libssd \
    libsubsystem_control \
    libsymphony-1.1.2 \
    libsymphonypower-1.1.2 \
    libsystem_health_mon \
    libthermalclient \
    libtime_genoff \
    libtinyxml \
    libtzdrmgenprov \
    libuicc \
    libulp2 \
    libvendorconn \
    libvoice-svc \
    libvss_common_core \
    libvss_common_idl \
    libvss_common_iface \
    libvss_nv_core \
    libvss_nv_idl \
    libvss_nv_iface \
    libwms \
    libwqe \
    libxml \
    libxt_native \
    libxtadapter \
    libxtwifi_ulp_adaptor \
    libdrmclearkeyplugin \
    sensors.ssc \
    libdrmwvmplugin \
    audio.a2dp.default \
    camera.msm8992 \
    sensors.hal.tof \
    sound_trigger.primary.msm8992 \
    libAlAisLib \
    libAlAisTune \
    libAlAisWrap \
    libHDR \
    libSubSystemShutdown \
    libVDBase \
    libVDLowLightAPI \
    libWVStreamControlAPI_L1 \
    libactuator_ad5823 \
    libactuator_ad5823_camcorder \
    libactuator_ad5823_camera \
    libactuator_bu64244gwz \
    libactuator_bu64244gwz_camcorder \
    libactuator_bu64244gwz_camera \
    libactuator_dw9714 \
    libactuator_dw9714_camcorder \
    libactuator_dw9714_camera \
    libactuator_dw9716 \
    libactuator_dw9716_camcorder \
    libactuator_dw9716_camera \
    libactuator_dw9761b \
    libactuator_dw9761b_camcorder \
    libactuator_dw9761b_camera \
    libactuator_lc898122 \
    libactuator_lc898122_camcorder \
    libactuator_lc898122_camera \
    libactuator_lc898122_claf \
    libactuator_lc898122_claf_camcorder \
    libactuator_lc898122_claf_camera \
    libactuator_lc898212xd \
    libactuator_lc898212xd_camcorder \
    libactuator_lc898212xd_camera \
    libactuator_ov8825 \
    libactuator_ov8825_camcorder \
    libactuator_ov8825_camera \
    libactuator_rohm_bu64243gwz \
    libactuator_rohm_bu64243gwz_camcorder \
    libactuator_rohm_bu64243gwz_camera \
    libadm \
    libalhdri \
    libalmcascore \
    libalmcaswrap \
    libarcsoft_beauty_shot \
    libchromaflash \
    libchromatix_imx234_common \
    libchromatix_imx234_common_open \
    libchromatix_imx234_common_video \
    libchromatix_imx234_common_video_open \
    libchromatix_imx234_cpp_flash_snapshot \
    libchromatix_imx234_cpp_flash_snapshot_open \
    libchromatix_imx234_cpp_hfr_120 \
    libchromatix_imx234_cpp_hfr_120_open \
    libchromatix_imx234_cpp_hfr_60 \
    libchromatix_imx234_cpp_hfr_60_open \
    libchromatix_imx234_cpp_liveshot \
    libchromatix_imx234_cpp_liveshot_open \
    libchromatix_imx234_cpp_panorama \
    libchromatix_imx234_cpp_panorama_open \
    libchromatix_imx234_cpp_preview \
    libchromatix_imx234_cpp_preview_open \
    libchromatix_imx234_cpp_snapshot \
    libchromatix_imx234_cpp_snapshot_hdr \
    libchromatix_imx234_cpp_snapshot_hdr_open \
    libchromatix_imx234_cpp_snapshot_open \
    libchromatix_imx234_cpp_video \
    libchromatix_imx234_cpp_video_hdr \
    libchromatix_imx234_cpp_video_hdr_open \
    libchromatix_imx234_cpp_video_open \
    libchromatix_imx234_default_video \
    libchromatix_imx234_default_video_open \
    libchromatix_imx234_hfr_120 \
    libchromatix_imx234_hfr_120_open \
    libchromatix_imx234_hfr_60 \
    libchromatix_imx234_hfr_60_open \
    libchromatix_imx234_hfr_90 \
    libchromatix_imx234_hfr_90_open \
    libchromatix_imx234_liveshot \
    libchromatix_imx234_liveshot_open \
    libchromatix_imx234_postproc \
    libchromatix_imx234_postproc_open \
    libchromatix_imx234_preview \
    libchromatix_imx234_preview_open \
    libchromatix_imx234_snapshot \
    libchromatix_imx234_snapshot_hdr \
    libchromatix_imx234_snapshot_hdr_open \
    libchromatix_imx234_snapshot_open \
    libchromatix_imx234_snapshot_panorama \
    libchromatix_imx234_snapshot_panorama_open \
    libchromatix_imx234_video_dual \
    libchromatix_imx234_video_dual_open \
    libchromatix_imx234_video_hdr \
    libchromatix_imx234_video_hdr_open \
    libchromatix_t4ka3_common \
    libchromatix_t4ka3_common_open \
    libchromatix_t4ka3_common_video \
    libchromatix_t4ka3_common_video_open \
    libchromatix_t4ka3_cpp_liveshot \
    libchromatix_t4ka3_cpp_liveshot_open \
    libchromatix_t4ka3_cpp_preview \
    libchromatix_t4ka3_cpp_preview_open \
    libchromatix_t4ka3_cpp_snapshot \
    libchromatix_t4ka3_cpp_snapshot_open \
    libchromatix_t4ka3_cpp_video \
    libchromatix_t4ka3_cpp_video_open \
    libchromatix_t4ka3_cpp_vt \
    libchromatix_t4ka3_cpp_vt_open \
    libchromatix_t4ka3_default_video \
    libchromatix_t4ka3_default_video_open \
    libchromatix_t4ka3_liveshot \
    libchromatix_t4ka3_liveshot_open \
    libchromatix_t4ka3_mms_video \
    libchromatix_t4ka3_mms_video_open \
    libchromatix_t4ka3_postproc \
    libchromatix_t4ka3_postproc_open \
    libchromatix_t4ka3_preview \
    libchromatix_t4ka3_preview_open \
    libchromatix_t4ka3_snapshot \
    libchromatix_t4ka3_snapshot_open \
    libchromatix_t4ka3_vt \
    libchromatix_t4ka3_vt_open \
    libdrc \
    libdrmdecrypt \
    libfastcvadsp_stub \
    libfastcvopt \
    libflash_pmic \
    libhwdaphal \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    liblgmda \
    libllvd_smore \
    libmm-qcamera \
    libmmcamera2_aec_lg \
    libmmcamera2_awb_lg \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_frame_algorithm \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_is \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_q3a_core \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_modules \
    libmmcamera2_vpe_module \
    libmmcamera2_wnr_module \
    libmmcamera_cac2_lib \
    libmmcamera_chromaflash_lib \
    libmmcamera_dbg \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_faceproc \
    libmmcamera_hdr_gb_lib \
    libmmcamera_imglib \
    libmmcamera_imx234 \
    libmmcamera_imx234_eeprom \
    libmmcamera_interface \
    libmmcamera_isp_abf44 \
    libmmcamera_isp_bcc44 \
    libmmcamera_isp_be_stats44 \
    libmmcamera_isp_bf_scale_stats44 \
    libmmcamera_isp_bf_stats44 \
    libmmcamera_isp_bg_stats44 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_bpc44 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_clf44 \
    libmmcamera_isp_color_correct40 \
    libmmcamera_isp_color_xform_encoder40 \
    libmmcamera_isp_color_xform_viewfinder40 \
    libmmcamera_isp_cs_stats44 \
    libmmcamera_isp_demosaic44 \
    libmmcamera_isp_demux40 \
    libmmcamera_isp_fovcrop_encoder40 \
    libmmcamera_isp_fovcrop_viewfinder40 \
    libmmcamera_isp_gamma44 \
    libmmcamera_isp_ihist_stats44 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm44 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff44 \
    libmmcamera_isp_rs_stats44 \
    libmmcamera_isp_scaler_encoder44 \
    libmmcamera_isp_scaler_viewfinder44 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_sub_module \
    libmmcamera_isp_wb40 \
    libmmcamera_llvd \
    libmmcamera_optizoom_lib \
    libmmcamera_ov5670 \
    libmmcamera_ov5670_eeprom \
    libmmcamera_ov5670w \
    libmmcamera_ov5670w_eeprom \
    libmmcamera_pdaf \
    libmmcamera_pdaf_v3 \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_stillmore_lib \
    libmmcamera_t4ka3 \
    libmmcamera_t4ka3_eeprom \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmcamera_trueportrait_lib \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmcamera_ubifocus_lib \
    libmmcamera_vpu_module \
    libmmipl \
    libmmjpeg \
    libmmjpeg_interface \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libmorpho_image_stab31 \
    libmorpho_superzoom \
    liboemcamera \
    liboemcrypto \
    libois_lc898122 \
    liboptizoom \
    libqct_resampler \
    libqomx_core \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libseemore \
    libsregex \
    libsurround_3mic_proc \
    libtar \
    libtrueportrait \
    libubifocus \
    libuiblur \
    libwvdrm_L1 \
    libwvm \
    libwvdrmengine \
    libqcbassboost \
    libqcomvoiceprocessingdescriptors \
    libqcreverb \
    libqcvirt \
    libCommandSvc \
    libbtnv \
    libfilterpack_facedetect \
    libloc_pla \
    libloc_stub \
    libmdtp \
    libthermalioctl \
    fastrpc_shell_0 \
    libapps_mem_heap \
    libdspCV_skel \
    libfastcvadsp \
    libfastcvadsp_skel \
    qcrilmsgtunnel \
    com.qti.snapdragon.sdk.display \
    com.quicinc.cne \
    izat.xt.srv \
    qcnvitems \
    qcrilhook \
    ATFWD-daemon \
    LKCore \
    RIDLClient.exe \
    adsprpcd \
    audioflacapp \
    bdaddr_loader \
    btnvtool \
    energy-awareness \
    hci_qcomm_init \
    rild \
    ims_rtp_daemon \
    imsdatadaemon \
    imsqmidaemon \
    imswmsproxy \
    ipacm-diag \
    irsc_util \
    loc_launcher \
    lowi-server \
    mm-qcamera-app \
    mm-qcamera-daemon \
    msm_irqbalance \
    netmgrd \
    pm-proxy \
    pm-service \
    qmuxd \
    qseecom_sample_client \
    qseecomd \
    qti \
    rfs_access \
    rmt_storage \
    sensors.qcom \
    slim_daemon \
    tftp_server \
    xtwifi-client \
    xtwifi-inet-agent
